CREATE TABLE instrutor (
  id BIGSERIAL PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  telefone VARCHAR(20) NOT NULL,
  cnh_categoria VARCHAR(3) NOT NULL
);

CREATE TABLE aluno (
  id BIGSERIAL PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  telefone VARCHAR(20) NOT NULL,
  cpf VARCHAR(14) NOT NULL UNIQUE
);
